services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=ninder
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ninder

  ninder:
    build: .
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - ninder
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  ninder:
